esphome:
  name: 3btn-test

esp8266:
  board: esp01_1m

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:
  password: "f725cd969b1b648cb3ff9974ff1ffb58"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "3Btn-Test Fallback Hotspot"
    password: "5rszVkcfLpfg"

captive_portal:

web_server:
  port: 80


dallas:
  - pin: GPIO14
  
sensor:
  - platform: dallas
    address:  0x46012066B1D79E28
    name: "3btn-test Temperature"
    unit_of_measurement: "°F"

  


binary_sensor:
  - platform: gpio
    pin: 
      number: GPIO13
      mode: INPUT_PULLUP
      inverted: FALSE
    name: '3btn Button 1'
    id: b11
  - platform: gpio
    pin: 
      number: GPIO5
      mode: INPUT_PULLUP
      inverted: FALSE
    name: '3btn Button 2'
    id: b22
  - platform: gpio
    pin: 
      number: GPIO4
      mode: INPUT_PULLUP
      inverted: FALSE
    name: '3btn Button 3'
    id: b33


light:
  - platform: fastled_clockless
    chipset: WS2812
    pin: GPIO12
    num_leds: 3
    rgb_order: GRB
    name: "3 LED Switch"
    id: LED_switch
    effects:
      # Use default parameters:
      - addressable_rainbow:
      - addressable_scan:
      - addressable_twinkle:
      - addressable_random_twinkle:
 
  - platform: partition
    name: "LED1"
    id: section1
    segments:
      - id: LED_switch
        from: 2
        to: 2
  - platform: partition
    name: "LED2"
    id: section2
    segments:
      - id: LED_switch
        from: 1
        to: 1
  - platform: partition
    name: "LED3"
    id: section3
    segments:
      - id: LED_switch
        from: 0
        to: 0
  
